# Generated by Django 4.2.4 on 2023-09-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('picture', models.FileField(default='sad.jpg', upload_to='blog_photos')),
            ],
        ),
    ]
